version: '3'
services:
  caddy:
    image: "elswork/arm-caddy"
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"    
    links:
      - gitea
      - wallabag
      - onetimesecret
      - psitransfer
      - calibre-web
    volumes:
      - /opt/caddy/.caddy:/root/.caddy
      - /opt/caddy/Caddyfile:/etc/Caddyfile
    restart: unless-stopped 
  wallabag:
    image: "walkingcrows/rpi-wallabag:2.3.1"
    volumes:
      - /opt/wallabag:/var/www/wallabag/data
    expose:
      - "80"
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://readlater.cloud.davidmichaelross.net
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    restart: unless-stopped 
  gitea:
    image: "kunde21/gitea-arm"
    volumes:
      - /opt/gitea:/data
    ports:
      - "222:22"
    expose:
      - "3000"
    restart: unless-stopped 
  embyserver:
    image: "emby/embyserver_arm32v7_neon"
    ports:
      - "8096:8096"
      - "8920:8920"
    expose:
      - "8096"
      - "8920"
    volumes:
      - /opt/embyserver/config:/config
      - /mnt/media/TVShows:/mnt/tv
      - /mnt/media/Movies:/mnt/movies
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped 
  heimdall:
    image: "linuxserver/heimdall"
    ports:
      - "80"
      - "443"
    volumes:
      - /opt/heimdall:/config
      - /opt/heimdall/env:/var/www/localhost/heimdall/.env
    environment:
      - PUID=1000
      - PGID=1000      
    restart: unless-stopped 
  onetimesecret:
    image: "dismantl/onetimesecret"
    build:
      context: ./onetimesecret
      dockerfile: Dockerfile
    restart: unless-stopped 
    ports:
      - "7143:7143"
    volumes:
      - '/opt/onetimesecret/config:/etc/onetime/config'
      - '/opt/onetimesecret/redis.conf:/etc/onetime/redis.conf'
      - '/opt/onetimesecret/redis:/var/lib/onetime/redis'
  psitransfer:
    image: "psitrax/psitransfer"
    build:
      context: ./psitransfer
      dockerfile: Dockerfile
    ports: 
      - "80"
    volumes:
      - '/opt/psitransfer/data:/data'
    restart: unless-stopped 
  syncthing:
    image: "linuxserver/syncthing"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
#      - UMASK_SET=022
    volumes:
      - /opt/syncthing:/config
      - /mnt/syncthing:/data1
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped 
  calibre-web:
    image: linuxserver/calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/syncthing/Calibre Library:/books
      - /opt/calibre-server:/config
    expose:
      - 8083
    restart: unless-stopped

